sudo: false

language: node_js
node_js:
  - "stable"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Test
      if: branch = master
      script:
        - npm test
    - stage: Deploy Windows & Mac
      if: branch = master
      os: osx
      osx_image: xcode10.1
      script:
        - npm run release -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy linux
      if: branch = master
      os: linux
      dist: trusty
      script:
        - npm run release -- --linux